### ISSUE TITLE
In case of multiple NICs (not connected), DeviceLocator.Discover() Throws Exception.

### ISSUE THREAD

**Issue by claudio-swone** [roddone/YeelightAPI#10]
Hey,
I have multiple NICs installed on my machine (some are virtual for Docker, some are just Ethernet, Wi-Fi, some are for HyperV).
If I'm connecting through Wi-Fi but also other adapters are enabled (enabled but not connected), I get this Exception when calling Discover method:

System.Net.Sockets.SocketException: "The requested address is not valid in its context"

If I disable all adapters apart from the one currently connected, then everything work as expected.

From what I understood, Discover method is sending the discover message using all NICs avaialble.
Maybe you could have an override, where one select the preferred NIC somehow, or maybe some sort of try catch logic to mitigate this kind of issue.

**Comment by roddone** [comment]
Hey, thanks for your feedback, I'm currently working on a solution in "safe-device-discovery" branch. It justs need some more tests, stay tunned !

**Comment by roddone** [comment]
Hey, 
I've tested my corrective and despite the fact i can't test your exact use case i think that'll do the job !
The package is now in version 1.4.0, it includes a safer version of DeviceLocator.Discover() and a new DeviceLocator.Discover(NetworkInterface) that allows you to discover devices through a specific NetworkInterface.

Please let me know it this corrects the problem so we can close this issue.

**Comment by claudio-swone** [comment]
Hey,
I'll download the latest, try it and give you some feedback.

**Comment by claudio-swone** [comment]
Hey, I've tested and it is working like a charm.
Also I've seen you introduced a try/catch logic which is actually working very good.

I'll close the issue.

Thx!
