### ISSUE TITLE
No devices found via SSDP

### ISSUE THREAD

**Issue by nithrous** [roddone/YeelightAPI#14]
Hi,

I have some Yeelight bulbs that works fine with native phone app and Google Home but i cannot find devices by YeelightApiConsoleTest app in discovery mode. It say that "No devices found via SSDP".
I also tried to use static ip addres taken from the app and use default port and get the error:

An error has occurred : No connection could be made because the target machine actively refused it 192.168.100.16:55443

**Comment by roddone** [comment]
Hi,

Thank you for your interest in YeelightAPI. 

Have you enabled the developer mode for your bulbs? This step is mandatory to use YeelightAPI.

Regards, 

Romain.

**Comment by nithrous** [comment]
@roddone thank you! My bulbs were not in developer mode, and now they works!
