### ISSUE TITLE
Set black Color

### ISSUE THREAD

**Issue by fabianoriccardi** [roddone/YeelightAPI#17]
Hi,
I would to set the "black" color instead to turn off the light, but it seems that 

`device.SetRGBColor(0, 0, 0);`

doesn't take any effect. If I try to set rgb(1,1,1) it works, but it really far from total blackness.

I've read Yeelight API documentation and (0,0,0) is a valid value

**Comment by roddone** [comment]
Hi, 

According to the Yeelight documentation, "0,0,0" is theorically a valid value but in practice it returns a "-5000, general error" which is the code for a general and / or unexpected error.

Furthermore, the "black" color does not exists. I assume your goal is to shut down the light, so please try the "SetPower(false)" instead.

Regards,

Romain.

**Comment by fabianoriccardi** [comment]
Thanks for the fast response, ok I was thinking that error -5000 was generated by your library, not Yeelight itself. Sorry.

However, my complete problem can be summarized by the following steps:

1. the light is on (i.e. red) 
2. it is turned off (set_power: "off") (smooth duration: 1000ms)
3. i would to turn on a different color (i.e. blue). (smooth duration:1000ms)

In the third step, you can notice that light's color is initially red fading to blue. 
My goal is a fading from off to blue. I can't find how to solve this "bug".

**Comment by roddone** [comment]
No problem, the error codes are not documented in the yeelight specifications.

To achieve what you are trying to do, you can use a "Scene" (cf set_scene in yeelight spec), for example :
```csharp
await device.TurnOn(); //ON
await device.SetRGBColor(255, 0, 0); //set to RED
await Task.Delay(1500);
await device.TurnOff(); //OFF
await Task.Delay(1500);
await device.SetScene(YeelightAPI.Models.Scene.Scene.FromRGBColor(0, 0, 255, 100)); //turn ON and set color to blue with 100% brightness
```
Note that I don't know how to adjust the smooth effect with Scenes.

**Comment by fabianoriccardi** [comment]
Ok, but Scene is like a sequence of commands or is it saved on Yeelight memory?
Because red -->blue transition was just an example, I can't create a scene for each color

**Comment by roddone** [comment]
Scene is just a way to set the smart LED directly to a specified state, if you want to specify a sequence of commands, maybe you are looking for Color Flows ? Take a look at YeelightAPI.Models.ColorFlow (cf start_cf in yeelight spec) : 
```csharp
ColorFlow flow = new ColorFlow(repeat, ColorFlowEndAction.Restore)
{
     new ColorFlowRGBExpression(255, 0, 0, 1, 500),
     new ColorFlowRGBExpression(0, 255, 0, 100, 500),
     new ColorFlowRGBExpression(0, 0, 255, 50, 500),
     new ColorFlowSleepExpression(2000),
     new ColorFlowTemperatureExpression(2700, 100, 500),
     new ColorFlowTemperatureExpression(5000, 1, 500)
};
await device.StartColorFlow(flow);
```

Anyway, I close this issue since there is no bug with the API.
