### ISSUE TITLE
[BUG] Performing actios without smooth transitio doels not work

### ISSUE THREAD

**Issue by Dainius14** [roddone/YeelightAPI#18]
**Describe the bug**

**To Reproduce**
1. Connect to the device.
2. Perform an action without passing the `smooth` parameter (null).

**Expected behavior**
Action immediately happens, e.g. device turns on, temperature is set. 

**Actual behavior**
Action does not happen. Exception is thrown `-5001 - invalid params`

**Environment (please complete the following information):**
 - OS: Windows 10 1903
 - .Net Core 3
 - Yeeight White 2 FW: 2.0.6_0035
 - Yeeight RGB 2 FW: 2.0.6_0051

I've spent so much time figuring out why it did not work oh my lord...

**Comment by roddone** [comment]
Hi, can you provide a code sample to help me reproduce the problem ?

**Comment by Dainius14** [comment]
You can recreate it in the tests by passing null as smooth parameter in methods:
SetPower, TurnOff, TurnOn, SetBrightness, SetColorTemperature, SetRGBColor, SetHSVColor. Output https://pastebin.com/EMciJfmW 

The tests are a little wrong though, because first you tests without smooth param, and then with smooth param, though not all applicable methods are passed the smooth param, so this also needs fixing. Also, tests show that everything is fine although half of the methods fail. And also for some reason my Yeelight is treated as BackgroundLight, although none of the methods work.

**Comment by roddone** [comment]
I can't reproduce the problem ... but I don't have the same devices as you to perform my tests (I only have Yeelight V1 RGB)
There could be a firmware compatibility issue with the smooth parameter, Yeelight expects 2 parameters : "smooth|sudden" and a duration. When no duration is expected the second parameter used to be ignored in V1, but I suspect in V2 it must be an integer in order to work.

I've made a possible fix in "tests-for-v2-bulbs" branch, since I can't test it by myself, can you test it and give me your feedback ?

**Comment by roddone** [comment]
> The tests are a little wrong though, because first you tests without smooth param, and then with smooth param, though not all applicable methods are passed the smooth param, so this also needs fixing. Also, tests show that everything is fine although half of the methods fail. And also for some reason my Yeelight is treated as BackgroundLight, although none of the methods work.

I agree, theses tests are just a quick way for me test all the methods with most common parameters. It cannot be trusted for industrial or unit testing

**Comment by Dainius14** [comment]
The strange thing is that it used to work fine for more than half a year
I've been using this library, something changed not so long ago (don't know
exactly when, since I did not need lamps very much during the summer lol)
probably after a firmware update. Alright, I'll check it when I can.

**Comment by Dainius14** [comment]
Works like a charm

**Comment by roddone** [comment]
Great, I will publish new nuget version quickly.
This will be a great opportunity to test my new azure devops pipelines 😁

**Comment by roddone** [comment]
fixed and new version 1.5.1 published and available on nuget ;)
