### ISSUE TITLE
Suggestion to change the meaning of repetition parameter for color flows

### ISSUE THREAD

**Issue by thoemmi** [roddone/YeelightAPI#22]
While fixing #21, I discovered a weird behavior in the Yeelight specification. If you execute this code
```csharp
await device.Flow()
    .RgbColor(255,   0, 0, 50, 2000)
    .RgbColor(  0, 255, 0, 50, 2000)
    .Play(ColorFlowEndAction.TurnOff, 4);
```
, I would expect the light to turn from red to green **four** times. However, it turns to green only **two** times. I consulted the specification, and in fact it states for the `start_cf` method:
> "count" is the total number of visible state changing before color flow stopped. 0 means infinite loop on the state changing.

Because the flow already consists of two state changes, the loops stops after 2 repetitions (2 state changes * 2 repetitions = count of 4).

That's not what I expected, and I guess other users may be surprised too. I've been always a fan of the [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). Therefore I suggest to change the semantic of the `repetition` parameter. I propose to change the implementation of `StartColorFlow` from 
```csharp
List<object> parameters = new List<object>()
{
    flow.RepetitionCount,
    (int)flow.EndAction,
    flow.GetColorFlowExpression()
};
```
to
```csharp
List<object> parameters = new List<object>()
{
    flow.RepetitionCount * flow.Count, // <-- multiply repetitions by number of flow actions
    (int)flow.EndAction,
    flow.GetColorFlowExpression()
};
```
How do you think about it?

**Comment by roddone** [comment]
I agree with this logic, the YeelightAPI sometimes need some "adjustements" ...
I will include this one in the next release, which will include #21 as well.
