### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BionicCode** [roddone/YeelightAPI#27]
**Description**
Async code in class `DeviceLocator` uses the blocking synchronous `Thread.Sleep()` in an asynchronous context. For efficiency it is recommended to prefer the awaitable Task library over the `Thread` API.

Check library for other occurrences.

**Expected behavior**
`DeviceLocator` line 158 should be changed to `await Task.Delay(TimeSpan.FromMilliseconds(10))`

**Comment by roddone** [comment]
You are right, this is how it should be done ;)
To be honest this is in my to-do list for a while but since it is not a bug I "forgot" to do the change 🙄
I will ship this in the next release.
