### ISSUE TITLE
Unable to detect Mi LED Smart Bulb[BUG]

### ISSUE THREAD

**Issue by Wintear91** [roddone/YeelightAPI#31]
downloaded this app and wanted to test out Mi LED Smart Bulb (White and Color).

Doesn't seen to be working. Isn't Mi bulbs and Yeelights using same protocol? I can't find related codes to do with Mi smart lights but keep getting Yeelight as the search result.

**Comment by roddone** [comment]
Hi, can you make sure the [developer mode](https://www.yeelight.com/faqs/lan_control) is enabled on your device ?

**Comment by Wintear91** [comment]
I See. I miss out that there is a need for this.

Thanks it work now.

Sent from Outlook<http://aka.ms/weboutlook>

________________________________
