### ISSUE TITLE
Call to DeviceLocator.Discover() in a Xamarin Android project does not return any devices

### ISSUE THREAD

**Issue by cjkarande** [roddone/YeelightAPI#32]
List<Device> miBulbs = await DeviceLocator.Discover();

Above call does not return any devices. Console Log shows following error

"type=1400 audit(0.0:219051): avc: denied { search } for name="net" dev="sysfs" ino=14407 scontext=u:r:untrusted_app:s0:c135,c264,c512,c768 tcontext=u:object_r:sysfs_net:s0 tclass=dir permissive=0"

**Comment by roddone** [comment]
Hi, please use the bug template the next time you create an issue, it describes two prerequisites : 
1. Check that your devices have the "developer mode" enabled
2. Check that your devices firmwares are up to date

Please check that both of these prerequisites are OK. If both of these prerequisites are OK, please provide a full code sample to help reproduce the problem. The log you provide is not really helpful.

Regards, 

Romain.

**Comment by cjkarande** [comment]
Hi @roddone ,
1) Yes Developer Mode is Enabled
2) Yes Device Firmware is Up to date

Issue here is that the Discover API call is working fine inside a Windows based Console Test App for the same device, however its Not working inside a Xamarin Forms Project. Also other Control APIs like Power, Brightness, etc. are working fine on the Device object constructed from a Host IPAddress in the Xamarin project. Its only the Discovery API that i am facing issue in a Xamarin project.
My current library configs are as follows
1) YeeLight API 1.7.0 
2) Project is using .Net Standard 2.0

**Comment by cjkarande** [comment]
using YeelightAPI;
using Device = YeelightAPI.Device;

DeviceLocator.OnDeviceFound += (sender, arg) => {
       Console.WriteLine($"Device found : {arg.Device}");
};

List<Device> devices = await DeviceLocator.Discover();

**Comment by roddone** [comment]
It seems like a network issue, i already have encountered some issues like that but I wasn't able to fix it because it was specific to the network / hardware.
Are you launching your app locally in your computer or directly on your mobile device? If launching on your computer, can you try to launch the app through Wi-Fi and ethernet to see if there is any difference?

**Comment by cjkarande** [comment]
Yes I hv read about some issues in desktop simulators. However, in my case i am running it directly on the android phone. On the other hand the Device Control APIs using Direct Host IP are working fine on Mobile.
For ex. the below calls are working fine. Issues is only wiyh Discover API
//////////////////////////////////////////////////////
Device device = new Device("192.168.1.xxx");
device.Connect();
await device.Toggle();
//////////////////////////////////////////////////////

One more observation, If this can help you locate the issue 
While i was trying alternate YeeLight Libraries, i found that the Discover API of the below library works fine on my mobile device and returns me the SmartBulb list in my n/w
https://github.com/SnakePin/yeelight-api-csharp

For ex. the following call from "yeelight-api-csharp" library call works fine on my mobile.
List<YeeLightAPI.YeeLightDevice> devices = DeviceLocator.DiscoverDevices(1000, 1);

**Comment by cjkarande** [comment]
Hi @roddone, today i debugged your Discover API and found that for some reason the Mobile Wifi Interface returns a Null GateWayAddress and hence skips execution of the succeeding logic. I observed that the GatewayAddress is getting used nowhere in your SSDP discovery logic so tried  commenting the below if condition after which the Discover API seems to work fine. Not sure why do we need to check presence of GatwayAddress.

if (addr != null && !addr.Address.ToString().Equals("0.0.0.0")) 
{
...
}

**Comment by thoemmi** [comment]
Maybe it's related to #25?

**Comment by roddone** [comment]
You're right @thoemmi, both issues seems similar and may be related, but proposed fixes are not the sames 🤔. 
@cjkarande can you locally try #25 and tell us if it fixes your issue ? If it does not I will considere this change in a future release 😉

**Comment by roddone** [comment]
I finally managed (and get some time) to reproduce the problem. Removing the test on the gateway adress seems to fix the problem, as you proposed.

Honnestly this is one of the first things i wrote two years ago and I don't remember why ...

I will ship the fix in the next release.
