### ISSUE TITLE
Q: Support for music mode?

### ISSUE THREAD

**Issue by bert2** [roddone/YeelightAPI#40]
I have hit the command quota with my Yeelight when trying to use it as an ambient light. I was setting it to the average screen color in a 100 ms interval. According to the documentation only 60 commands per second are allowed _unless_ the device is in "music mode".

I see that I can activate music mode via `Device.StartMusicMode(string hostName, int port)`. I also understand that this means I have to create a secondary TCP server which my Yeelight can connect to and then feed it the commands over this channel.

However, it seems there is no API support for this? Meaning I will have to generate the JSON for the commands myself and can't use your library for music mode connections. Is this correct?

**Comment by roddone** [comment]
Hi, thank you for your interest in YeelightAPI.

You are right, for the moment YeelightAPI is not designed to befenit fully of the music mode.
This has never been reported/requested and I don't use it either so it hasn't been my priority, until now. 

I was wondering what features would be included in next release, this one will surely be!

**Comment by bert2** [comment]
That's great to hear! Thanks for all the effort you put into this 👍 

In the meantime I'm letting my Yeelight connect to my application like so (in case anyone stumbles upon the same problem):

```csharp
var localAddr = NetworkInterface
    .GetAllNetworkInterfaces()
    .Single(ifc => ifc.Name == "Ethernet")
    .GetIPProperties()
    .UnicastAddresses
    .Single(a => a.Address.AddressFamily == AddressFamily.InterNetwork)
    .Address;
const int port = 12345;

var listener = new TcpListener(localAddr, port);
listener.Start();
Debug.Assert(await device.StartMusicMode(localAddr.ToString(), port));
using var musicDevice = await listener.AcceptTcpClientAsync();
```

And then I can flood it with `set_rgb` commands like a maniac 😄 

```csharp
var cmd = $"{{\"id\": {DateTime.Now.Ticks}, \"method\": \"set_rgb\", \"params\":[{color.ToRgb()}, \"sudden\", 0]}}\r\n";
_ = musicDevice.Client.Send(Encoding.UTF8.GetBytes(cmd));
```

**Comment by roddone** [comment]
I reopen because this is an issue which is not resolved yet. I will close it with a PR from `feature/music-mode` branch

**Comment by roddone** [comment]
@bert2 I think I'm pretty close to the final version of the music mode feature.

In the meantime can you try the latest [Beta version which is available on nuget](https://www.nuget.org/packages/YeelightAPI/1.9.0-beta-CI-20200804-094711)  and give me your feedback ?
1.9.0-beta-CI-20200804-094711

**Comment by bert2** [comment]
Nice, gonna test it as soon as I can!

**Comment by bert2** [comment]
Works like a charm! 👍

**Comment by bert2** [comment]
@roddone I have a tiny request: can you make it so that `DeviceGroup.ToString()` returns `DeviceGroup.Name`? If you want I can open an issue or a PR for that, but I figured that might be overkill.

**Comment by roddone** [comment]
Of course I can. I would like ToString() to return a string like `{groupName} ({count} devices)`. Does it suits your needs ?

**Comment by bert2** [comment]
That'd work just fine, thank you!

**Comment by bert2** [comment]
Thanks! Finally I can open a club in my living room! 😄

**Comment by roddone** [comment]
1.9 is published on nuget, you can start partying ;)
