### ISSUE TITLE
[Feature-request][Question]

### ISSUE THREAD

**Issue by d8ahazard** [roddone/YeelightAPI#49]
Hello, this is more of a feature request/inquiry, versus a bug.

I am curious - for the setRgbColor function, is this sent over HTTP?

I would like to use this API with an application of mine that sends streaming color data to lights in realtime. Ideally, this would be done over UDP for speed of transmission/repetition.

As such, I'm wondering if Yeelight has a "streaming" protocol, and if so, if this API exposes it in any way. If there is and it's not exposed - would it be possible to support this functionality? Looking to send color data anywhere from 30-60 times per second.

**Comment by roddone** [comment]
Hi, 
YeelightAPI is "just" a wrapper around [Yeelight Protocol](https://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf).
This protocol does absolutely **NOT** relies on HTTP. It is based on **UDP** for device discovery (through an SSDP-like protocol) and **TCP** for device control.

This is designed this way by Yeelight and cannot be changed.
