### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HugoB07** [roddone/YeelightAPI#56]
Hello, I have an error on connect my device : No connection could be established because the target computer expressly refused it

Can you help me ? Thanks

**Comment by roddone** [comment]
Hi, 
It is more likely to be a network error rather than a problem with the library.

Please make sure you've followed the requirements about [enabling the developer mode](https://www.yeelight.com/faqs/lan_control)

**Comment by HugoB07** [comment]
thank you, I had to install an old version of yeelight because my xiamo bulb no longer has the lan control in the latest version

**Comment by roddone** [comment]
so there is nothing to fix in this API and we can close the issue ?

**Comment by HugoB07** [comment]
Yes, the issue is close !
