### ISSUE TITLE
The same device is discovered multiple times

### ISSUE THREAD

**Issue by thoemmi** [roddone/YeelightAPI#8]
I noticed that you're sending the discovery message [three times](https://github.com/roddone/YeelightAPI/blob/fe258c545e7e57e68238ca8693c1e443a01d994f/YeelightAPI/DeviceLocator.cs#L54). Because the `devices` property isn't locked, I sometimes get two or even three `Device` instances, although I only have on physical device.
Is there a reason why you sending the message three times? And if this is really necessary, consider using `lock` for exclusive access to `devices`, e.g.
```csharp
lock (devices)
{
    //add only if no device already matching
    if (!devices.Any(d => d.Hostname == device.Hostname))
    {
        devices.Add(device);
    }
}
```
(`devices` can be simple `List<Device>`, by the way. `ConcurrentBag` doesn't help you, because between the calls to `Any` and `Add`, another thread might add the same device)

**Comment by roddone** [comment]
By experience, when the device has a low wi-fi signal it appears that it does not send the response to the discovery message, so I send it threee times to maximize the chances to get a response.
But you're right, the ConcurrentBag does not help, I will use a classical List with a lock instead.
